### ISSUE TITLE
Settle on Schema for Current Tables

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/ongenome_schema#1]
This is going to happen kind of organically as we work on this, but I have already made some changes to the schema so at some point lets discuss and make sure everyone is on the same page

**Comment by adf-ncgr** [comment]
@ctcncgr did our recent discussion merit closure of this issue?

**Comment by ctcncgr** [comment]
@adf-ncgr I think this also can be closed.  We may want to reopen it when we revisit certain tables at a later date, such as 'treatment'.
