### ISSUE TITLE
Sample loading: All ncbi accessions should be loaded into sample.ncbi_accessions field.

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ongenome_schema#12]
Some are getting to the sample.other_attributes field. Should all be in sample.ncbi_accessions.
Example:
other_attributes  | cultivar:Negro jamapa;infraspecies:None;application:Nitrate fertilizer;tissue:Leaf 21 DAI;key:SRR1569385;sample_name:Leaf 21 DAI (SRR1569385);bioproject_accession:PRJNA210619;biosample_accession:SAMN02226070;organism:Phaseolus vulgaris
ncbi_accessions   | sra_accession:SRS696939;sra_run:SRR1569385;sra_study:SRP046307

**Comment by ctcncgr** [comment]
fixed.  This now grabs all SRA, bioproject and biosample accessions
