### ISSUE TITLE
Exemplars for each dataset

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/ongenome_schema#19]
To link a dataset to the gene page, need an exemplar gene model.  Currently maintaining the list in the code for the expression summary page.  Better option is to have it in the database.  

ongenome.dataset can have a new column 'exemplar'.  After adding it to table definition Connor will need to modify (minor) the loader script to include this column.

Will affect and hence need to modify code for expression summary  and lis-species pages.

**Comment by sdash-github** [comment]
lis-stage:
ALTER TABLE ongenome.dataset ADD COLUMN exemplar VARCHAR(64);
ALTER TABLE;

**Comment by sdash-github** [comment]
@lis-stage:
UPDATE ongenome.dataset SET exemplar='cicar.ICC4958.gnm2.ann1.Ca_01885' WHERE accession_no='cicar1'; 
UPDATE ongenome.dataset SET exemplar='Phvul.001G011300.v1.0' WHERE accession_no='phavu1'; 
UPDATE ongenome.dataset SET exemplar='cajca.ICPL87119.gnm1.ann1.C.cajan_07765' WHERE accession_no='cajca1'; 
UPDATE ongenome.dataset SET exemplar='vigun.IT97K-499-35.gnm1.ann1.Vigun01g004300' WHERE accession_no='vigun1';

 accession_no |                  exemplar
--------------+---------------------------------------------
 cicar1       | cicar.ICC4958.gnm2.ann1.Ca_01885
 phavu1       | Phvul.001G011300.v1.0
 cajca1       | cajca.ICPL87119.gnm1.ann1.C.cajan_07765
 vigun1       | vigun.IT97K-499-35.gnm1.ann1.Vigun01g004300

**Comment by sdash-github** [comment]
NEXT STEP:  For Connor
Modify @ lis-stage, function load_dataset() in OngenomeLoaders.py
Assigning to Connor now.  
(Will load cicar2 and glyma1 at @lis-satge after this)

**Comment by ctcncgr** [comment]
This is done.  You now will load the dataset then you can provide the gene at any time when you have found the one you want by running the loader like below:
```
python ongenome_loader.py --example_gene cicar.ICC4958.gnm2.ann1.Ca_01885 --example_dataset cicar1
```

This will update the table and assign the example

**Comment by sdash-github** [comment]
SUCCESS. cicar2 loaded successfully including the exemplar with the new column code change by Connor.
Closing.
