### ISSUE TITLE
Review Current Loader Design and Philosophy

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/ongenome_schema#3]
We should meet as a group to do this and just make sure that everything works in a way that makes sense to everyone.  Also we need to discuss the logging style (briefly).  

I like the way that I have this setup but it may be too verbose for some.  You can set the level

**Comment by adf-ncgr** [comment]
@ctcncgr did our recent discussion merit closure of this other issue?

**Comment by ctcncgr** [comment]
@adf-ncgr I think this is done.  We will reopen when and if needed.
