### ISSUE TITLE
Make parser arguments less ambiguous

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/ongenome_schema#5]
@adf-ncgr had commented that the flags for the loader may be a little ambiguous based on what they perform.  I agree with this.

I have changed them to --gff and --gfflist, from --orgniamgff and --organismlist.  These are shorter and still have the same descriptions which describe in detail what they are.

What do you guys think of those flags?

**Comment by adf-ncgr** [comment]
sorry, didn't notice you had asked my opinion- looks good...
